name: persesrd
channels:
  - conda-forge
  - defaults
#  - omnia-dev
  - omnia
  - rdkit
dependencies:
  - python <3.9 # TODO: Should support 3.9. Perhaps just an issue with other conda pkgs such as pymbar?
  - setuptools
  - fire
  - joblib
  - numpy >=1.14
  - scipy
  - numexpr
#  - autograd
#  - pymbar
  - openmm >=7.4.2
#  - openmoltools # may need to sort out ambermini/ambertools/parmed dependencies (we don't want ambertools)
#  - openmmtools # may need to sort out ambermini/ambertools/parmed dependencies
  - numba
  - netcdf4
  - matplotlib
  - seaborn
  - mdtraj
#  - pdbfixer
  - lxml
  - networkx >=2.0
  - rdkit
  - dask
  - distributed
  - progressbar2
  # parmed is LGPL / GPL
#  - parmed # may need to sort out ambermini/ambertools/parmed dependencies
  - tqdm
  - nose
  - nose-timer
  - openforcefield
  - sphinx
